[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "xxx"


[auth.microsoft]
client_id = "xxx"
client_secret = "xxx"
server_metadata_url = (
    "https://login.microsoftonline.com/{tenant}/v2.0/.well-known/openid-configuration"
)